Develop
mate-academy/Museum_2 pull request #251
Opened 2023-03-01 00:59 UTC by NazikVr

[DEMO LINK](https://nazikvr.github.io/Museum_2/).

2023-03-01 08:13 UTC, tetiana-ivanchenko requested changes
fix all points from the checklist
https://github.com/mate-academy/Museum_2/blob/master/checklist.md
points: 3, 4, 7 (you form didn't submitt at all)
![image](https://user-images.githubusercontent.com/59209337/222081410-2a02b6cc-64be-4518-87b8-85660a0b0694.png)
on click for:
adress should be a link to google maps
phone should open ability to call
email should open email template

2023-03-05 12:04 UTC, agniya-i requested changes
Good job! 

Remove outline for this input 
<img width="503" alt="Screenshot 2023-03-05 at 12 59 56" src="https://user-images.githubusercontent.com/32853034/222959241-ec846171-643e-472c-a601-d8ef1e246fd8.png">

It would be nice if I couldn't scroll the page when the menu is open

https://user-images.githubusercontent.com/32853034/222959270-a2aafd2a-fcd9-4ed6-bcf5-48ca643c5bae.mov

2023-03-05 15:53 UTC, polosanya requested changes
Hi, I see you haven't fixed previous comments, maybe you did not push your changes?
If you have any questions, please ask them in fe_chat and tag mentors. It will be faster because your answers in GitHub will be visible to the mentor only after you re-request review 🙂

2023-03-06 12:38 UTC, anstsot requested changes
Great job, let's fix few last places:
1. the distance is different
![image](https://user-images.githubusercontent.com/22824431/223112074-741393fe-c28a-4c66-aaf2-721f8cc1a7c8.png)
2. the block is too high (check the design please) 
![image](https://user-images.githubusercontent.com/22824431/223112205-ea423e9e-927a-4df3-a0b7-072c31da7548.png)
3. top block has a big distance as well
![image](https://user-images.githubusercontent.com/22824431/223112335-421daf74-199e-43a9-900a-ddc6e8af0935.png)
4. it would be better to change the navigation height to: 100vh to be showed on the whole screen
![image](https://user-images.githubusercontent.com/22824431/223112589-98f683ef-2a92-4676-b94d-6c9dc9006032.png)

2023-03-08 08:46 UTC, mykhalenych approved these changes

2025-10-08 16:39 UTC, closed without merging